import { ReportesMesPlantadorDto } from "../../application/dto/ReportesMesPlantador.dto";

export class ReportesMesPlantadorEntity {
    private constructor(
        public readonly id: number | undefined,
        public readonly direccion_completa: string,
        public readonly fecha_proyectada_mision: Date,
        public readonly nro_nuevos_contactos: number,
        public readonly nro_nuevos_gdc: number,
        public readonly nro_nuevas_conversiones: number,
        public readonly nro_consolidados: number,
        public readonly nro_discipulados: number,
        public readonly nro_bautizados_agua: number,
        public readonly nro_nuevas_personas_gdc: number,
        public readonly nro_nuevos_lideres_gdc: number,
        public readonly nro_creyentes: number,
        public readonly nro_miembros: number,
        public readonly nro_lideres_gdc: number,
        public readonly total_personas_gdc: number,
        public readonly total_personas_discipulados: number,
        public readonly visita_pastor_iglesia_central: string,
        public readonly visita_supervisor_distrital: string,
        public readonly comentario: string,
    ) { }

    public static crear({
        id,
        direccion_completa,
        fecha_proyectada_mision,
        nro_nuevos_contactos,
        nro_nuevos_gdc,
        nro_nuevas_conversiones,
        nro_consolidados,
        nro_discipulados,
        nro_bautizados_agua,
        nro_nuevas_personas_gdc,
        nro_nuevos_lideres_gdc,
        nro_creyentes,
        nro_miembros,
        nro_lideres_gdc,
        total_personas_gdc,
        total_personas_discipulados,
        visita_pastor_iglesia_central,
        visita_supervisor_distrital,
        comentario,
    }: ReportesMesPlantadorDto): ReportesMesPlantadorEntity {
        return new ReportesMesPlantadorEntity(
            id,
            direccion_completa,
            fecha_proyectada_mision,
            nro_nuevos_contactos,
            nro_nuevos_gdc,
            nro_nuevas_conversiones,
            nro_consolidados,
            nro_discipulados,
            nro_bautizados_agua,
            nro_nuevas_personas_gdc,
            nro_nuevos_lideres_gdc,
            nro_creyentes,
            nro_miembros,
            nro_lideres_gdc,
            total_personas_gdc,
            total_personas_discipulados,
            visita_pastor_iglesia_central,
            visita_supervisor_distrital,
            comentario,
        );
    }
}
